// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "b9ae99e935309e9c70483a269806ebb8efab35271577de5489f8038ed3d36b65")
