// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "dee065191f65bae803bcbdaef047419578c9a7686ede70f9b4b823c0cf28c94d")
